### PR TITLE
Fix pause (help) screen output - #35

### PR DESCRIPTION
**Pull request by wyattearp**
Attempting to address the help not fitting on the screen and the same sort of thing when using the hex command.

Tested as follows:
* used standard putty terminal, min, max --> `help` pages on any key
* used standard putty terminal, min, max --> `hex` pages on any key, quits on ~~`q`~~ `x`

I'm sure this isn't perfect, but I figured it's easier comment on code when it exists :) - any feedback is appreciated

**NOTE**: it appears in one of my commits the line-endings didn't get ignored -- suggest checking that drop-down on the review page to make it easier to look at (sorry!)

### CODE REVIEW

**Comment by DangerousPrototypes** [comment]
I'm going to pull this one to a test branch to play with it a bit. The only thing that stands out to me is that everywhere else we're using 'x' to exit, instead of 'q'. I'd like to standardize on one or the other, I'm not married to either though.

**Comment by wyattearp** [comment]
> I'm going to pull this one to a test branch to play with it a bit. The only thing that stands out to me is that everywhere else we're using 'x' to exit, instead of 'q'. I'd like to standardize on one or the other, I'm not married to either though.

`x` makes sense to me but it looks like you merged before I could get to it (stupid real work being in the way :) )

**Comment by DangerousPrototypes** [comment]
I'm not totally sure, but the commit doesn't include an updated en-us.json, so I'm guessing you added the new string to all the translations manually? There is a python script that updates the base.h and all the translations using the defaults in en-us.h, which makes it a ton easier. I'll just run that to refresh everything, here is a reference:

https://firmware.buspirate.com/development/translation#process-to-h-header-file

**Comment by DangerousPrototypes** [comment]
This looks good to me. The only reason I haven't merged is because I can't figure out how to do so without a full replacement of ui_help.c and ui_term.c the "official" way. If you can push files with the other style line endings so we get a good diff, I'll merge. The other option is I can drop your working files in my local copy and handle line endings there, but it always feels rude to not accept a pull request :)

**Comment by wyattearp** [comment]
Ok - I based this off of what was in the main, which is CRLF instead of LF - hopefully that helps make it look cleaner!

**Comment by DangerousPrototypes** [comment]
Thanks! Perfect. I'm going to merge, and then run json2h.py to get the new translation tag into the translation system.

**Pull request merged**
