### PR TITLE
UART: Implement CTS/RTS flow control, add option to invert signals

### PR DESCRIPTION
**Pull request by mblsha**
* CTS is implemented in hardware (uart_set_hw_flow).
* RTS is software-defined, since otherwise it doesn't get properly raised when inverted signals are used.

Tested this with a Sharp PC-G850 pocket computer:
* TX connected to Pin6 (RXD)
* RX connected to Pin7 (TXD)
* CTS connected to Pin4 (RTS)
* RTS connected to Pin9 (CTS)

For reference PC-G850 works with these settings:
* UART speed: 1200 baud (later model variants seem to work at 9600, didn't test them yet)
* Data bits: 8
* Parity: None
* Stop bits: 1
* Hardware flow control: RTS/CTS
* Signal inversion: Inverted

### CODE REVIEW

**Comment by thestumbler** [comment]
A Sharp PC-G850? I'm impressed. I used a Tandy PC-2 (a re-badged Sharp PC-1500) extensively back in the 80s.

**Comment by henrygab** [comment]
@mblsha -- I took a quick look.  Can you please do the following additional steps?

```
cd ./translation
python ./json2h.py
```

This should cause a few more files to be added, and is necessary to prevent corruption for non-EN-US translations.  I expect the following additional files will get changed:

* `en-us.json` (generated from `en-us.h`)
* `bs-ba.h` (generated based on new `en-us.json` and `bs-ba.json`)
* `it-it.h` (generated based on new `en-us.json` and `it-it.json`)
* `pl-pl.h` (generated based on new `en-us.json` and `pl-pl.json`)
* `zh-cn.h` (generated based on new `en-us.json` and `zh-cn.json`)

Thanks!

**Comment by mblsha** [comment]
Tried running `python ./json2h.py` but seems that something strange is happening with the line-endings probably, which causes too many changes to be flagged.

(I also had similar problems when both vim/vscode/sublime-text reformatted the .c files I edited, so I had to resort to TextMate that only did the white-space trimming without line-ending conversion)

**Comment by mblsha** [comment]
(did unix2dos on the affected files, and it helped reduce number of changes)

**Comment by thestumbler** [comment]
There are some settings in your git config that helps avoid the line endings problem. I'm not sure what Ian's policy is, but I typically make remote repos always use Unix line endings. And most of the machines I use, and Windows machines also via WSL, I use Unix line endings locally as well. When working in a "native" Windows environment where DOS endings are the convention, the appropriate git config settings will handle the conversions seamlessly. 

I've carefully avoided saying just what those settings are 8-) you may have noticed. I'm not at a computer now to check, but also, there are some different opinions out there about the "correct" way to do this.

**Comment by mblsha** [comment]
Thanks Chris! I think it might be core.autocrlf (which is `false` in my config), but it's my text editors (and Python??) which write the new endings, and my git doesn't normalize them. According to [stackoverflow](https://stackoverflow.com/a/2825829) `.gitattributes` might be the way to make git work with that, and I tried doing it but I probably misconfigured something since it didn't help.

**Comment by thestumbler** [comment]
@mblsha took a look at my setup. I have `autocrlf`  set to `input`. This seems to be one common way of handling things. You can read about it [here](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration). But my case has always been the remote repo uses Unix line endings. This repository may be different?

Another important one in my experience is `filemode = False`. This prevents changes in a file's permissions or ownership from triggering an unintended change. This is almost always the desired functionality, especially if users of the repository are using different operating and/or file systems. 

It was difficult for me to initially understand that these various settings, in general, are not known to the remote repository. They are independently maintained by each user locally, and may be different (by design). This [reddit thread](https://www.reddit.com/r/git/comments/cqgtgw/is_there_any_way_to_100_enforce_certain_line/) is one such discussion on the line endings history and different opinions.

Finally, in 2024, one can almost exclusively work with Unix line endings on all platforms even Windows. Nearly every modern-ish Windows IDE and editor can read / write files with Unix endings, either automatically or by an easy configuration setting. I've worked with a few clients over the past couple of years for which some Windows work was required, and I can't remember this ever being a problem (keeping everything with Unix endings). The only time it pops up is if someone pulls / clones from an outside repo that was setup to use CR/LF endings, or a random text file has those endings.

**Comment by henrygab** [comment]
Looks good to me.  Note: Windows builds currently fail.  I'm going to fix that, and ask forgiveness later.

**Comment by henrygab** [comment]
> it seems like henry has proposed an alternative that might make the python step unnecessary

Sadly, I'm not that good... However, I **_have_** improved the python script, and will be changing the generated headers to make it more clear what needs to occur when adding an entirely new string, and what needs to occur when adding an entirely new translation.

**Pull request merged**
