### PR TITLE
QoL changes ... for consideration 

### PR DESCRIPTION
**Pull request by henrygab**
There are some substantive improvements around inter-core messaging.
This PR is intended as a DRAFT / Untested changes, primarily to allow easier review/commenting/discussion.

* Helper functions for inter-core messaging add ~136 bytes to flash.  The inclusion of a counter byte in the ICM value was responsible for only ~8 of those bytes, and seems efficiently optimized by the compiler.
* Reduced precious RAM usage by 16 bytes
* Restricting invalid values being set from configuration only added ~8 bytes(!) to flash.
* Cannot seem to get CMake to require C23... sigh.
* Lots of comment-only changes
* Lots of formatting-only changes
* A few TODO/BUGBUG items noted (but not addressed)

### CODE REVIEW

**Comment by DangerousPrototypes** [comment]
This is looking really good. Some of the diffs are a bit confusing, I'm going to make a pull request from your repo to a new branch so I can have a closer look.

**Comment by henrygab** [comment]
Yeah, this branch wasn't really intended for direct PR, more for review and commentary.  I am happy to cleanup and present a branch with more targeted updates (e.g., removing comments or the like, focusing on the inter-core messaging cleanup, focusing on the RGB cleanup, etc.).

**Comment by henrygab** [comment]
Importantly, please note that some of the more recent RGB changes have **_not_** been tested.  _Caveat Emptor!_

Otherwise, there's a need to define better names for some of the intercore messaging values.

**Comment by henrygab** [comment]
Closing as these are now in other PRs (except RGB ... which is coming soon)

**Pull request closed without merging**
