### PR TITLE
Add legacy mode for third parties flashrom avrdude

### PR DESCRIPTION
**Pull request by therealdreg**
Bus Pirate v5* & v6-> (flashrom, avrdude & asprogrammer dreg mod, from #81 )

The idea here is to create something small and simple that works with third parties, not to implement everything. So the code I've written is a bit tricky (for example, I’m telling flashrom that I’m a Bus Pirate v2.5 (HW) so that it keeps the UART baud rate at 115200 by default...)

------

image

image

-----

image

----

uf2 files:

[build.zip](https://github.com/user-attachments/files/16751972/build.zip)

----

## Example flashrom

```
flashrom.exe --progress -V -c "W25Q64JV-.Q" -p buspirate_spi:dev=COM5,spispeed=8M -r flash_content.img
```

## Example avrdude

```
avrdude.exe -V -c buspirate -p m328p -P COM5 -b 115200 -U flash:r:"C:\Users\regue\Desktop\readed.bin":r
```

### CODE REVIEW

**Comment by therealdreg** [comment]
@DangerousPrototypes all ready! merge it if you like it!

**Comment by AreYouLoco** [comment]
Just tested it with flashrom on some random chip and it worked.

Only thing that is missing pin labels on the LCD and maybe a way to get out of the legacy binmode without disconnecting and connecting.

**Comment by therealdreg** [comment]
> Just tested it with flashrom on some random chip and it worked.
> 
> Only thing that is missing pin labels on the LCD and maybe a way to get out of the legacy binmode without disconnecting and connecting.

rigth, its a minor issue, It will improve it in a future PR, thx for your feedback @AreYouLoco

**Comment by therealdreg** [comment]
@DangerousPrototypes can you run the workflow again plz?

**Comment by therealdreg** [comment]
I’ve compiled it manually on Windows, and it works. From looking at the workflows on macOS and Ubuntu, it compiles there as well, so everything is good.

**Pull request merged**
