### PR TITLE
Fix: update for pip and docker

### PR DESCRIPTION
**Pull request by wyattearp**
Sadly the docker build has been broken because the systems started enforcing the "don't break system packages" for pip installs.

To stay closer to the actually build instructions, I've updated to install cmake from the repo as opposed to pip, this should really be problematic because nothing fancy is happening in cmake.

Additionally, I finally took the time to setup a docker hub account to host an image. I'm happy to create a buspirate org and leave it up there, but also, I didn't want to do that without asking because it wouldn't be owned by the real maintainers :)

### CODE REVIEW

**Comment by wyattearp** [comment]
Huh - that's neat. It looks like there's something up with the Windows build. 

```
CMake Error at CMakeLists.txt:11 (include):
  include could not find requested file:

    C:\Users\runneradmin/.pico-sdk/cmake/pico-vscode.cmake
    
```

This was definitely something I saw at the top of the cmake file that I'm wondering if it was supposed to make it into main at this time?

**Comment by wyattearp** [comment]
I've got a change that looks like this will make WSL function correctly with picotool. Seems I've also been hitting this issue as well

https://github.com/raspberrypi/pico-sdk/pull/1820#issuecomment-2291371915

I'm going to tweak the container again and see if this resolves the build to make it operational on both.

Moving back to draft.

**Comment by DangerousPrototypes** [comment]
Thank you for the updates and attention to the docker scripts. I'll away your final pull request.

**Comment by wyattearp** [comment]
This should address the previous limitations on the docker container, also fixing the fact that the `picotool` wasn't actually being found correctly and doing the CMake things it was supposed to be doing.

Ref:
* https://github.com/raspberrypi/pico-sdk/pull/1820#issuecomment-2291371915
* https://github.com/raspberrypi/pico-sdk/pull/1820#issuecomment-2291611448


@DangerousPrototypes -- know any WSL users that can test out a windows .devcontainer in vscode? :-D

**Comment by wyattearp** [comment]
@DangerousPrototypes  -- for what it's worth, both of the build did complete successfully, but it looks like the GH actions cancelled them -- you can see it got to the linking step in the logs and did what it was supposed to.

**Pull request merged**
